server {
    listen 80;
    server_name localhost;
    
    root /usr/share/nginx/html;
    index index.html;

    # Serve static files directly
    location / {
        # The magic line: try file -> try folder -> fallback to index.html
        try_files $uri $uri/ /index.html;
    }
}