name: frontend
description: "PC Building website."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1  # Updated to ensure null safety and compatibility with Dart 3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter_riverpod: ^2.5.1 # Updated to latest compatible version
  flutter_dotenv: ^6.0.0
  json_annotation: ^4.9.0
  intl_utils: ^2.8.11  # Downgraded to resolve analyzer conflict
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13  # Stable version compatible with Dart 3.9.2
  json_serializable: ^6.8.0  # Compatible with build_runner 2.4.13

dependency_overrides:
  analyzer: ^6.0.0  # Aligns with build_runner, json_serializable, and intl_utils
  test_api: 0.7.6  # Matches flutter_test requirement

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/uk_flag.png
    - assets/tr_flag.png
    - assets/pl_flag.png